[2024-08-07T13:11:24.058+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T13:11:24.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_bigquery.extract_orders manual__2024-08-07T13:06:17+00:00 [queued]>
[2024-08-07T13:11:24.078+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_bigquery.extract_orders manual__2024-08-07T13:06:17+00:00 [queued]>
[2024-08-07T13:11:24.078+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-07T13:11:24.086+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_orders> on 2024-08-07 13:06:17+00:00
[2024-08-07T13:11:24.094+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=446) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T13:11:24.097+0000] {standard_task_runner.py:64} INFO - Started process 459 to run task
[2024-08-07T13:11:24.102+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mongodb_to_bigquery', 'extract_orders', 'manual__2024-08-07T13:06:17+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/mongodb_to_bigquery.py', '--cfg-path', '/tmp/tmpyky2o97_']
[2024-08-07T13:11:24.104+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask extract_orders
[2024-08-07T13:11:24.138+0000] {task_command.py:426} INFO - Running <TaskInstance: mongodb_to_bigquery.extract_orders manual__2024-08-07T13:06:17+00:00 [running]> on host a4ff97c14a38
[2024-08-07T13:11:24.205+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_to_bigquery' AIRFLOW_CTX_TASK_ID='extract_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T13:06:17+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T13:06:17+00:00'
[2024-08-07T13:11:24.206+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T13:11:24.219+0000] {warnings.py:112} WARNING - /app/data_engineering/api_connectors/mongodb.py:24: UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
  data = list(self.db[collection_name].find(filters))

[2024-08-07T13:11:25.312+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T13:11:25.315+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/data_engineering/api_connectors/mongodb.py", line 27, in fetch_data
    module = import_module.import_module(collection_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'import_module'
[2024-08-07T13:11:25.343+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mongodb_to_bigquery, task_id=extract_orders, run_id=manual__2024-08-07T13:06:17+00:00, execution_date=20240807T130617, start_date=20240807T131124, end_date=20240807T131125
[2024-08-07T13:11:25.357+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task extract_orders ('function' object has no attribute 'import_module'; 459)
[2024-08-07T13:11:25.405+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T13:11:25.415+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
