[2024-08-07T13:03:27.356+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T13:03:27.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_bigquery.extract_products scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-07T13:03:27.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_bigquery.extract_products scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-07T13:03:27.448+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-07T13:03:27.469+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_products> on 2024-08-06 00:00:00+00:00
[2024-08-07T13:03:27.476+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=195) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T13:03:27.478+0000] {standard_task_runner.py:64} INFO - Started process 213 to run task
[2024-08-07T13:03:27.485+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mongodb_to_bigquery', 'extract_products', 'scheduled__2024-08-06T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/mongodb_to_bigquery.py', '--cfg-path', '/tmp/tmpoxm2zdoe']
[2024-08-07T13:03:27.491+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask extract_products
[2024-08-07T13:03:27.559+0000] {task_command.py:426} INFO - Running <TaskInstance: mongodb_to_bigquery.extract_products scheduled__2024-08-06T00:00:00+00:00 [running]> on host a4ff97c14a38
[2024-08-07T13:03:27.639+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_to_bigquery' AIRFLOW_CTX_TASK_ID='extract_products' AIRFLOW_CTX_EXECUTION_DATE='2024-08-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-06T00:00:00+00:00'
[2024-08-07T13:03:27.640+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T13:03:27.659+0000] {warnings.py:112} WARNING - /app/data_engineering/api_connectors/mongodb.py:24: UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
  data = list(self.db[collection_name].find(filters))

[2024-08-07T13:03:28.793+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T13:03:28.800+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/data_engineering/api_connectors/mongodb.py", line 27, in fetch_data
    module = import_module.import_module(collection_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'import_module'
[2024-08-07T13:03:28.842+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mongodb_to_bigquery, task_id=extract_products, run_id=scheduled__2024-08-06T00:00:00+00:00, execution_date=20240806T000000, start_date=20240807T130327, end_date=20240807T130328
[2024-08-07T13:03:28.865+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task extract_products ('function' object has no attribute 'import_module'; 213)
[2024-08-07T13:03:28.911+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T13:03:29.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
