[2024-08-07T14:43:39.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:43:39.781+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_bigquery.load_orders manual__2024-08-07T14:38:14.199786+00:00 [queued]>
[2024-08-07T14:43:39.787+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_bigquery.load_orders manual__2024-08-07T14:38:14.199786+00:00 [queued]>
[2024-08-07T14:43:39.787+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-07T14:43:39.798+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_orders> on 2024-08-07 14:38:14.199786+00:00
[2024-08-07T14:43:39.811+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:43:39.813+0000] {standard_task_runner.py:64} INFO - Started process 288 to run task
[2024-08-07T14:43:39.818+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mongodb_to_bigquery', 'load_orders', 'manual__2024-08-07T14:38:14.199786+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/mongodb_to_bigquery.py', '--cfg-path', '/tmp/tmpj3d1n2hv']
[2024-08-07T14:43:39.823+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask load_orders
[2024-08-07T14:43:39.903+0000] {task_command.py:426} INFO - Running <TaskInstance: mongodb_to_bigquery.load_orders manual__2024-08-07T14:38:14.199786+00:00 [running]> on host 721db11e5d12
[2024-08-07T14:43:40.141+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_to_bigquery' AIRFLOW_CTX_TASK_ID='load_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T14:38:14.199786+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T14:38:14.199786+00:00'
[2024-08-07T14:43:40.144+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:43:40.634+0000] {logging_mixin.py:188} INFO - ☑️ Dataset fictive_company already exists
[2024-08-07T14:43:40.975+0000] {logging_mixin.py:188} INFO - ☑️ Table mycenter-425712.fictive_company.orders already exists.
[2024-08-07T14:43:44.968+0000] {logging_mixin.py:188} INFO - 
 ✅ Loaded 2000 rows into fictive_company:orders.
[2024-08-07T14:43:45.382+0000] {logging_mixin.py:188} INFO - 
❕number rows before =  4000
[2024-08-07T14:43:52.529+0000] {logging_mixin.py:188} INFO - ❕number rows after =  2000
[2024-08-07T14:43:52.539+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-07T14:43:52.540+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:43:52.568+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mongodb_to_bigquery, task_id=load_orders, run_id=manual__2024-08-07T14:38:14.199786+00:00, execution_date=20240807T143814, start_date=20240807T144339, end_date=20240807T144352
[2024-08-07T14:43:52.637+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T14:43:52.654+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:43:52.655+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
