[2024-08-07T14:43:23.520+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:43:23.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_bigquery.load_orders manual__2024-08-07T14:43:12.057956+00:00 [queued]>
[2024-08-07T14:43:23.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_bigquery.load_orders manual__2024-08-07T14:43:12.057956+00:00 [queued]>
[2024-08-07T14:43:23.604+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T14:43:23.630+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_orders> on 2024-08-07 14:43:12.057956+00:00
[2024-08-07T14:43:23.642+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:43:23.652+0000] {standard_task_runner.py:64} INFO - Started process 256 to run task
[2024-08-07T14:43:23.656+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mongodb_to_bigquery', 'load_orders', 'manual__2024-08-07T14:43:12.057956+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/mongodb_to_bigquery.py', '--cfg-path', '/tmp/tmpsuulpuwv']
[2024-08-07T14:43:23.661+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask load_orders
[2024-08-07T14:43:23.751+0000] {task_command.py:426} INFO - Running <TaskInstance: mongodb_to_bigquery.load_orders manual__2024-08-07T14:43:12.057956+00:00 [running]> on host 721db11e5d12
[2024-08-07T14:43:24.042+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_to_bigquery' AIRFLOW_CTX_TASK_ID='load_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T14:43:12.057956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T14:43:12.057956+00:00'
[2024-08-07T14:43:24.045+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:43:24.591+0000] {logging_mixin.py:188} INFO - ☑️ Dataset fictive_company already exists
[2024-08-07T14:43:24.917+0000] {logging_mixin.py:188} INFO - ☑️ Table mycenter-425712.fictive_company.orders already exists.
[2024-08-07T14:43:28.686+0000] {logging_mixin.py:188} INFO - 
 ✅ Loaded 2000 rows into fictive_company:orders.
[2024-08-07T14:43:29.001+0000] {logging_mixin.py:188} INFO - 
❕number rows before =  4000
[2024-08-07T14:43:36.168+0000] {logging_mixin.py:188} INFO - ❕number rows after =  2000
[2024-08-07T14:43:36.171+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-07T14:43:36.172+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:43:36.200+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mongodb_to_bigquery, task_id=load_orders, run_id=manual__2024-08-07T14:43:12.057956+00:00, execution_date=20240807T144312, start_date=20240807T144323, end_date=20240807T144336
[2024-08-07T14:43:36.238+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T14:43:36.272+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:43:36.274+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
