[2024-08-07T13:06:20.074+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T13:06:20.091+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_bigquery.extract_products manual__2024-08-07T13:06:17+00:00 [queued]>
[2024-08-07T13:06:20.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_bigquery.extract_products manual__2024-08-07T13:06:17+00:00 [queued]>
[2024-08-07T13:06:20.094+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T13:06:20.100+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_products> on 2024-08-07 13:06:17+00:00
[2024-08-07T13:06:20.105+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T13:06:20.106+0000] {standard_task_runner.py:64} INFO - Started process 363 to run task
[2024-08-07T13:06:20.111+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mongodb_to_bigquery', 'extract_products', 'manual__2024-08-07T13:06:17+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/mongodb_to_bigquery.py', '--cfg-path', '/tmp/tmp9fug1ro2']
[2024-08-07T13:06:20.114+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask extract_products
[2024-08-07T13:06:20.145+0000] {task_command.py:426} INFO - Running <TaskInstance: mongodb_to_bigquery.extract_products manual__2024-08-07T13:06:17+00:00 [running]> on host a4ff97c14a38
[2024-08-07T13:06:20.192+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_to_bigquery' AIRFLOW_CTX_TASK_ID='extract_products' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T13:06:17+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T13:06:17+00:00'
[2024-08-07T13:06:20.193+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T13:06:20.208+0000] {warnings.py:112} WARNING - /app/data_engineering/api_connectors/mongodb.py:24: UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
  data = list(self.db[collection_name].find(filters))

[2024-08-07T13:06:21.264+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T13:06:21.266+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/data_engineering/api_connectors/mongodb.py", line 27, in fetch_data
    module = import_module.import_module(collection_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'import_module'
[2024-08-07T13:06:21.286+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=mongodb_to_bigquery, task_id=extract_products, run_id=manual__2024-08-07T13:06:17+00:00, execution_date=20240807T130617, start_date=20240807T130620, end_date=20240807T130621
[2024-08-07T13:06:21.297+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task extract_products ('function' object has no attribute 'import_module'; 363)
[2024-08-07T13:06:21.320+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T13:06:21.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
